language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN=f8a404d6-8b4e-4320-b709-590f7a6d33df

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always